Solve sum
js-tasks-ru/vue-20230516_alexey-lytovchenko pull request #1
Opened 2023-06-06 16:49 UTC by AlexeyLyt

2023-06-06 16:49 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @ShGKme должен запустить тесты.

2023-06-06 20:27 UTC, AlexeyLyt commented
Извините, если некорректно закоммитал задания из разных блоков в один ПР, так делать можно или лучше по каждому блоку отдельно ПР делать?
(если отдельно ПР на каждый блок заданий - выходит нужно под каждый блок отдельно ветку создавать..?)

2023-06-06 23:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-06-06 23:16 UTC, ShGKme requested changes
В `01-basics/02-VueCalculator` и `01-basics/04-MeetupTitle` есть проблема в работе с радиокнопками, остальные задачи приняты.

2023-06-06 23:16 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/script.js
> +});
Хотя в свойствах экземпляра есть свойство `$data` с данными компонента, обычно всегда работают через короткие (проксирующие) свойства

`{{ counter }}`

2023-06-06 23:16 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
>          </div>
Сейчас эти радиокнопки связаны с состоянием компонента односторонне. Выбор нового оператора радиокнопками приведёт к корректному обновлению состоянию приложения. Но, если в состоянии приложения будет изменён выбранный оператор иным путём, то радиокнопки никак не будут обновлены. Их состояние "выбранности" сейчас никак не связано с состоянием приложения.

Должно быть двустороннее связывание, чтобы не было проблемы, когда состояние на странице и в приложении отличаются.

2023-06-06 23:16 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
> +        </span>
Аналогичная проблема

2023-06-06 23:17 UTC, ShGKme commented
> Извините, если некорректно закоммитал задания из разных блоков в один ПР, так делать можно или лучше по каждому блоку отдельно ПР делать?
> (если отдельно ПР на каждый блок заданий - выходит нужно под каждый блок отдельно ветку создавать..?)

Вы можете сдавать любое количество задач в одном PR. Но PR будет принят только, когда все добавленные в него задачи решены и проходят тесты (иначе получится принятие нерешённое задачи).

Создание отдельной ветки тут не поможет, так как задачи всё равно добавляются в `master`. Новые ветки будут включать в себя добавленные и предыдущие задачи.

2023-06-09 10:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-06-09 10:28 UTC, ShGKme requested changes
Требуется убрать обработчики событий, которые уже добавляются через `v-model`.

2023-06-09 10:28 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
> +          <label><input  v-model="meetupId" type="radio" name="meetupId" :value="item" @change="onSelectMeetup" /> {{ item }}</label>
`v-model` уже организует двустороннее связывание, добавляя обработчик `@change`. В итоге у этого элемента дважды обрабатывается `change`. Это не приводит к проблемам, но это добавляет лишний код, усложняет понимание того, что происходит в компоненте (зачем-то добавлен отдельный обработчик - значит у этого есть своя цель?) и может стать потенциальной ошибкой в будущем (есть два источника с реакцией на изменение, сейчас одинаковой реакцией, но в результате ошибки может стать разная реакция).

2023-06-09 10:28 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +          <label><input v-model="operator" type="radio" name="operator" value="divide" @click="onSelectOperator" /> ➗</label>
Аналогично здесь

2023-06-09 16:18 UTC, AlexeyLyt commented on 01-basics/02-VueCalculator/index.html
> +          <label><input v-model="operator" type="radio" name="operator" value="divide" @click="onSelectOperator" /> ➗</label>
Понял, да, поспешил
Спасибо большое за разъяснение!

2023-06-14 15:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-06-14 15:06 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-06-14 15:07 UTC, merged